# Generated by Django 5.2.1 on 2025-11-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0005_remove_postlike_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
