# Generated by Django 5.2.1 on 2025-11-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0006_users_avatar_alter_users_role_alter_users_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='github_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
