# Generated by Django 5.2.1 on 2025-12-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0008_alter_users_password_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
    ]
